{{- if .Values.configMaps.apiConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: api
  annotations:
    description: "Configuration for the VAT Filing Pricing Tool API"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  {{- range $key, $value := .Values.configMaps.apiConfig.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.configMaps.webConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: web
  annotations:
    description: "Configuration for the VAT Filing Pricing Tool Web Frontend"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  {{- range $key, $value := .Values.configMaps.webConfig.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.configMaps.nginxConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: web
  annotations:
    description: "Nginx configuration for the VAT Filing Pricing Tool Web Frontend"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  {{- range $key, $value := .Values.configMaps.nginxConfig.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}