# This template creates a Kubernetes Secret containing sensitive configuration data
# for the VAT Filing Pricing Tool application. For production environments, consider
# using external secret management solutions like Azure Key Vault with the CSI driver
# instead of storing sensitive values in Helm values files.
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    description: "Sensitive configuration for the VAT Filing Pricing Tool"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: {{ .Values.secrets.type | default "Opaque" }}
data:
  # Database connection strings
  sql-connection-string: {{ .Values.secrets.data.sql-connection-string | b64enc }}
  cosmos-connection-string: {{ .Values.secrets.data.cosmos-connection-string | b64enc }}
  redis-connection-string: {{ .Values.secrets.data.redis-connection-string | b64enc }}
  storage-connection-string: {{ .Values.secrets.data.storage-connection-string | b64enc }}
  
  # Azure AD authentication credentials
  azure-ad-tenant-id: {{ .Values.secrets.data.azure-ad-tenant-id | b64enc }}
  azure-ad-client-id: {{ .Values.secrets.data.azure-ad-client-id | b64enc }}
  azure-ad-client-secret: {{ .Values.secrets.data.azure-ad-client-secret | b64enc }}
  azure-ad-authority: {{ .Values.secrets.data.azure-ad-authority | b64enc }}
  
  # Monitoring credentials
  appinsights-instrumentation-key: {{ .Values.secrets.data.appinsights-instrumentation-key | b64enc }}
{{- end }}