apiVersion: v1
kind: Secret
metadata:
  name: vatfilingpricingtool-secrets
  namespace: vatfilingpricingtool
  labels:
    app: vatfilingpricingtool
    component: api
    part-of: vatfilingpricingtool
    managed-by: kubectl
  annotations:
    description: "Sensitive configuration for the VAT Filing Pricing Tool API"
    azure-key-vault-sync: "true"
type: Opaque
data:
  # Database connection strings
  sql-connection-string: ${SQL_CONNECTION_STRING_BASE64}
  cosmos-connection-string: ${COSMOS_CONNECTION_STRING_BASE64}
  redis-connection-string: ${REDIS_CONNECTION_STRING_BASE64}
  storage-connection-string: ${STORAGE_CONNECTION_STRING_BASE64}
  
  # Authentication credentials
  azure-ad-tenant-id: ${AZURE_AD_TENANT_ID_BASE64}
  azure-ad-client-id: ${AZURE_AD_CLIENT_ID_BASE64}
  azure-ad-client-secret: ${AZURE_AD_CLIENT_SECRET_BASE64}
  
  # Application monitoring
  appinsights-instrumentation-key: ${APPINSIGHTS_INSTRUMENTATION_KEY_BASE64}
  
  # Security
  jwt-secret-key: ${JWT_SECRET_KEY_BASE64}
  
  # External service integration
  erp-api-key: ${ERP_API_KEY_BASE64}
  ocr-api-key: ${OCR_API_KEY_BASE64}
  email-api-key: ${EMAIL_API_KEY_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-auth
  namespace: vatfilingpricingtool
  labels:
    app: vatfilingpricingtool
    component: infrastructure
    part-of: vatfilingpricingtool
    managed-by: kubectl
  annotations:
    description: "Azure Container Registry authentication credentials"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}