apiVersion: v2
name: vatfilingpricingtool
version: 1.0.0
appVersion: 1.0.0
description: A Helm chart for deploying the VAT Filing Pricing Tool application to Kubernetes
type: application
keywords:
  - vat
  - tax
  - pricing
  - finance
  - calculation
home: https://vatfilingpricingtool.com
sources:
  - https://github.com/organization/vatfilingpricingtool
maintainers:
  - name: DevOps Team
    email: devops@vatfilingpricingtool.com
dependencies:
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.10.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: cert-manager
    version: 1.10.0
    repository: https://charts.jetstack.io
    condition: certificates.enabled