using System; // Version: 6.0.0 - Core .NET functionality

namespace VatFilingPricingTool.Domain.Enums
{
    /// <summary>
    /// Defines the available formats for reports generated by the VAT Filing Pricing Tool.
    /// This enum is used throughout the application to specify the desired output format for reports.
    /// </summary>
    public enum ReportFormat
    {
        /// <summary>
        /// Portable Document Format. A standard document format that preserves document formatting 
        /// and enables file sharing. The format is useful when you want to preserve exact formatting 
        /// and ensure the document looks the same regardless of where it's viewed.
        /// </summary>
        PDF = 0,

        /// <summary>
        /// Microsoft Excel format. Allows for spreadsheet functionality and data manipulation.
        /// Useful when recipients need to perform additional calculations or data analysis.
        /// </summary>
        Excel = 1,

        /// <summary>
        /// Comma Separated Values format. A simple text format for representing tabular data.
        /// Useful for data integration with other systems or applications.
        /// </summary>
        CSV = 2,

        /// <summary>
        /// HyperText Markup Language format. Web-based format for displaying reports in browsers.
        /// Useful for online viewing and web-based reporting dashboards.
        /// </summary>
        HTML = 3
    }
}